### ISSUE TITLE
Using layman in a multi-command binding doesn't work

### ISSUE THREAD

**Issue by matclab** [frap129/swlm#5]
I use the following i3 config:
 ```
set $layout_mode "None | Autotiling | Grid | MasterStack  (n|a|g|m)"
mode $layout_mode {
    bindsym n nop layman layout none; mode default
    bindsym a nop layman layout Autotiling; mode default
    bindsym g nop layman layout Grid; mode default
    bindsym m nop layman layout MasterStack; mode default
    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
## Windows // Layout manager mode //  p ##
bindsym $mod+p mode $layout_mode

````

Which leads to the following error:
```
getattr(): attribute name must be string
restarting after exception:
ERROR:root:getattr(): attribute name must be string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/layman/layman.py", line 341, in init
    self.eventConn.main()
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3.10/site-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.10/site-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/usr/lib/python3.10/site-packages/layman/layman.py", line 223, in onBinding
    layout = getattr(self.userLayouts[name], name)
TypeError: getattr(): attribute name must be string
```

One fix would be to change the `if "nop layman …` in command by something like:
```python
        if command.startswith("nop layman layout "):
            shortName = command.split(';')[0].strip()
```
or something more robust using a regexp to allow *layman command* sot sit in between other commands.

**Comment by matclab** [comment]
Yes. Perfect !
Thank you for your quick support. It is very much appreciated.
I still have some glitches. But I'll keep you informed in new issues if needed.
